# Generated by Django 3.2 on 2021-04-16 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('url', models.CharField(max_length=255)),
                ('image_front_small_url', models.CharField(max_length=45)),
                ('energy_kj', models.CharField(max_length=45)),
                ('energy_kcal', models.CharField(max_length=45)),
                ('fat', models.CharField(max_length=45)),
                ('fiber', models.CharField(max_length=45)),
                ('proteins', models.CharField(max_length=45)),
                ('salt', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitution.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='substitution.product')),
            ],
        ),
    ]
