# Generated by Django 3.2 on 2021-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_front_small_url',
            field=models.CharField(max_length=255),
        ),
    ]
